[tool.poetry]
package-mode=false

[tool.poetry.dependencies]
python = "^3.12"
aiogram = "^3.15.0"
pydantic-settings = "^2.6.1"
sqlalchemy = "^2.0.36"
psycopg2 = "^2.9.10"
asyncpg = "^0.30.0"
alembic = "^1.14.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
